### ISSUE TITLE
deps "murmur3 @ 01abb7a" not found.

### ISSUE THREAD

**Issue by YanB25** [kaist-cp/pebr-benchmark#41]
Running `git submodule update --init --recursive` throws an error.

It seems that the repo "murmur3 @ 01abb7a" does not exist.

Is it a private repo and you forget to make it public?

The failed link: https://github.com/jeehoonkang/murmur3.git

**Comment by jeehoonkang** [comment]
@YanB25 thank you for reporting this! I believe now this issue is resolved.

Closing, but please feel free to reopen this if the problem continues to exist!
